<ul class="nav">
    <?php
    /** @var $container \Zend\Navigation\Navigation */
    $container = $this->container;
    
    ?>

    <?php 
    foreach ($container as $page) : 
        $hasChildren = $page->hasPages(); 
    ?>
    <?php if (!$hasChildren) : ?>
        <li class="dropdown <?php echo $page->isActive() ? ' active' : ''; ?>">
        <a href="<?php echo $page->getHref() ?>">
            <?php echo $page->getLabel() ?>
        </a>
    <?php else: ?>
        <li class="<?php echo $page->isActive() ? 'active' : ''; ?>"> 

        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $page->getLabel() ?></a>
        
            <ul class="dropdown-menu">
                <?php foreach ($page as $child) : ?>
                <?php if ($child->get("divider")) : ?>
                    <li class="divider">
                <?php else: ?>
                    <li>
                        <a href="<?php echo $child->getHref();?>">
                            <?php if ($child->get('icon')) : ?>
                            <i class="<?php echo $child->get('icon'); ?>"></i>
                            <?php endif; ?>
                            <?php echo $child->getLabel(); ?>
                        </a>
                <?php endif; ?>
                </li>
                <?php endforeach; ?> 
            </ul>
    <?php endif; ?>
    </li>
    <?php endforeach; ?>
    
</ul>
