<?php
use SMCommon\View\Helper\FormatDate;
// A partial for displaying a purchase.

/* @var $this SMCommon\View\Renderer\PhpRenderer */
/* @var $purchase \Application\Entity\Purchase */
$purchase = $this->purchase;
?>

<table class="table table-condensed">
	<tr>
		<td>Amount</td>
		<td><?php echo number_format($purchase->getAmount(), 2) ?> CHF</td>
	</tr>
	<tr>
		<td>Store</td>
		<td><?php echo $purchase->getStore()?></td>
	</tr>
	<tr>
		<td>Date</td>
		<td><?php echo $this->formatDate($purchase->getDate(), FormatDate::FORMAT_DATE);?></td>
	</tr>
	<tr>
		<td>Receipt number</td>
		<td><?php echo ($purchase->getSlipNumber() ? $purchase->getSlipNumber() : "-")?></td>
	</tr>
	<tr>
		<td>Description</td>
		<td><?php echo $purchase->getDescription() ?></td>
	</tr>
	<tr>
		<td>User</td>
		<td><?php
			$userUrl = $this->url('user/action', array(
				'id' => $purchase->getUser()->getId(),
			));
			echo $this->prettyprint()->link($userUrl, $purchase->getUser()->getFullname());
			?>
		</td>
	</tr>
	<tr>
		<td>Created</td>
		<td>
			<?php echo $this->formatDate($purchase->getCreated());?>
			<?php if ($purchase->getCreatedWithAPI()): ?>
				(API)
			<?php endif;?>
		</td>
	</tr>
	<?php if ($purchase->getCreated() != $purchase->getLastModified()) : ?>
	<tr>
		<td>Last edited</td>
		<td><?php echo $this->formatDate($purchase->getLastModified());?></td>
	</tr>
	<?php endif;?>
</table>