<?php
use Application\View\Helper\UserTable;
use Application\Entity\User;
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Benutzer', $this->account->getName());

$table = $this->usertable();
$table->setData($this->users);

// Actions

$table->addColumn(array(
	'headTitle' 	=> 'Aktionen',
	'dataMethod'	=> function(User $user) {
		$result = '';

		$removeUserUrl = $this->url('account/users', array(
			'action' 			=> 'remove',
			'userid' 			=> $user->getId(),
			'accountid'			=> $this->account->getId(),
		));

		$result .= $this->prettyprint()->button($removeUserUrl, 'Entfernen', 'danger');

		return $result;
	}
));

echo $table;

$addUserUrl = $this->url('account/users', array(
	'action' 			=> 'add',
	'accountid'			=> $this->account->getId(),
));
?>

<span class="pull-right">
	<?php echo $this->prettyprint()->button($addUserUrl, 'Benutzer hinzufügen')?>
</span>
