<?php
use Application\Entity\Account;
use Application\Entity\Purchase;
use SMCommon\View\Helper\FormatDate;
/* @var $this SMCommon\View\Renderer\PhpRenderer */

/* @var $dateFormatter SMCommon\View\Helper\FormatDate */
$dateFormatter = $this->plugin('formatDate');
$subtitle = $dateFormatter->formatRange($this->startDate, $this->endDate, FormatDate::FORMAT_DATE);

$params = array(
		'action' 	=> "select-date",
		'accountid'	=> $this->account->getId(),
);
$url = $this->url('accounts/list-action', $params);

echo $this->pageHeader($this->account->getName(), '<a href="'.$url .'">'. $subtitle .'</a>');

$table = $this->purchasetable();
$table->setData($this->purchases);
$table->addUserColumns();

$table->addColumn(array(
	'headTitle' 	=> 'Aktionen',
	'dataMethod'	=> function(Purchase $purchase) {
		$url = $this->url('accounts/purchases', array(
			'accountid' 	=> $this->account->getId(),
			'purchaseid'	=> $purchase->getId(),
		));
		return $this->prettyprint()->button($url, 'Details');
	}
));

echo $table;

$addPurchsaeUrl = $this->url('accounts/purchases', array(
	'action' 		=> 'add',
	'accountid'		=> $this->account->getId(),
));
?>


<span class="pull-right"><a class="btn" href="<?php echo $addPurchsaeUrl ?>">Einkauf hinzufügen</a></span>
