<?php
use Application\Entity\Account;
use Application\Entity\Purchase;
use SMCommon\View\Helper\FormatDate;
/* @var $this SMCommon\View\Renderer\PhpRenderer */

/* @var $dateFormatter SMCommon\View\Helper\FormatDate */
$dateFormatter = $this->plugin('formatDate');
$subtitle = $dateFormatter->formatRange($this->startDate, $this->endDate, FormatDate::FORMAT_DATE);

$params = array(
		'action' 	=> "select-date",
		'accountid'	=> $this->account->getId(),
);
$url = $this->url('accounts/list-action', $params);

echo $this->pageHeader($this->account->getName(), '<a href="'.$url .'">'. $subtitle .'</a>');

// Perhaps we have a archived account
if ($this->account->isArchived()) {
    echo $this->prettyprint()->alert("This account is archived.", "warning");
}

$table = $this->purchasetable();
$table->setData($this->purchases);
$table->addUserColumns($this->account->getUsers());

$table->addColumn(array(
	'headTitle' 	=> 'Actions',
	'dataMethod'	=> function(Purchase $purchase) {
		$url = $this->url('accounts/purchases', array(
			'accountid' 	=> $this->account->getId(),
			'purchaseid'	=> $purchase->getId(),
		));
		return $this->prettyprint()->button($url, 'Details');
	}
));

?>
<h3>Purchases</h3>
<?php

echo $table;

$addPurchsaeUrl = $this->url('accounts/purchases', array(
	'action' 		=> 'add',
	'accountid'		=> $this->account->getId(),
));
?>

<span class="pull-right"><a class="btn" href="<?php echo $addPurchsaeUrl ?>">Add Purchase</a></span>

<?php
// Prepare urls for statistics
$startdate = $this->startDate->format('Y-m-d');
$enddate = $this->endDate->format('Y-m-d');
$monthlyExpensesUrl = $this->graphs()->monthlyExpensesGraph(
	$this->account,
	$this->endDate->format('Y-m'),
	600,
    350
);
$storesCountUrl = $this->graphs()->storeCountGraph(
	$this->account,
	$startdate,
	$enddate,
 	-1,
	600,
	400
);
$storesAmountUrl = $this->graphs()->storeAmountGraph(
	$this->account,
	$startdate,
	$enddate,
 	-1,
	600,
	400
);
?>

<h3>Statistics</h3>
<div class="row">
	<div class="span3"></div>
	<div class="span6"><img src="<?php echo $monthlyExpensesUrl; ?>"></div>
	<div class="span3"></div>
</div>
<div class="row">
	<div class="span6"><img src="<?php echo $storesCountUrl; ?>"></div>
	<div class="span6"><img src="<?php echo $storesAmountUrl; ?>"></div>
</div>

