<?php
use SMCommon\View\Helper\FormatDate;
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Einkauf');

/* @var $purchase \Application\Entity\Purchase */
$purchase = $this->purchase;
?>

<div class="row">
	<div class="span6">
		<h3>Übersicht</h3>
		<table class="table table-condensed">
			<tr>
				<td>Betrag</td>
				<td><?php echo number_format($purchase->getAmount(), 2)?> CHF</td>
			</tr>
			<tr>
				<td>Geschäft</td>
				<td><?php echo $purchase->getStore()?></td>
			</tr>
			<tr>
				<td>Datum</td>
				<td><?php echo $this->formatDate($purchase->getDate(), FormatDate::FORMAT_DATE);?></td>
			</tr>
		</table>
	</div>

	<div class="span6">
		<h3>Benutzer</h3>
		<?php
		echo $this->partial('partial/user/span6-gravatar', array(
			'user' => $this->purchase->getUser(),
		));
		?>
	</div>
</div>

<div class="row">
	<div class="span12">
		<h3>Details</h3>
		<?php
		echo $this->partial('partial/purchase', array(
			'purchase' => $this->purchase,
		));
		?>
	</div>
</div>
<div class="pull-right">
	<?php
	$editUrl = $this->url('accounts/purchases', array('action' => 'edit'), array(), true);
	echo $this->prettyprint()->button($editUrl, 'Bearbeiten');
	?>
</div>