<?php
/**
 * A partial for displaying a purchase.
 *
 * Params:
 * user: required. The user you want to display
 * rows: optional.	Additional rows you want to display. Array of key value pairs,
 * 					where the key is the title and the value the title.
 */



/* @var $this SMCommon\View\Renderer\PhpRenderer */
/* @var $user \Application\Entity\User */
$user = $this->user;
$email = $user->getEmailAddress();

// Additional rows
$rows = ($this->rows != NULL ? $this->rows : array());
?>
<div class="row">
	<table class="table table-condensed span5">
		<tr>
			<td>Username</td>
			<td><?php echo $user->getUsername()?></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><a href="mailto:<?php echo $email;?>"><?php echo $email; ?></a></td>
		</tr>
		<?php foreach ($rows as $title => $value): ?>
		<tr>
			<td><?php echo $title?></td>
			<td><?php echo $value?></td>
		</tr>
		<?php endforeach;?>
	</table>

	<div class="pull-right">
		<?php echo $this->gravatar($email)?>
	</div>
</div>