<?php 
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Benutzer Löschen', $this->user->getFullname());
?>

<div class="alert alert-block alert-error">
<h4>Achtung!</h4>
Möchten Sie den Benutzer "<?php echo $this->user->getFullname();?>" wirklich löschen? Dieser Vorgang kann nicht Rückgängig gemacht werden.
</div>

<?php
echo $this->bootstrapForm($this->form, 'horizontal');
?>