<?php 
use Application\Entity\User;
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Benutzer');

$table = $this->table();
$table->setData($this->users);

$table->addColumn(array('Name', 'getFullname'));
$table->addColumn(array('Benutzername', 'getUsername'));

$table->addColumn(array(
	'headTitle' 	=> 'Email',
	'dataMethod'	=> function(User $user) {
		$email = $user->getEmailAddress();
		return $this->prettyprint()->email($email);	
	}
));

// Actions!
$table->addColumn(array(
	'headTitle' 	=> 'Aktionen',
	'dataMethod'	=> function(User $user){
		$editURL = $this->url('user/action', array('action' => 'edit', 'id' => $user->getId()));
		return $this->prettyprint()->button($editURL, 'Edit');
	}
));

echo $table;

?>