<?php
use Application\Entity\Bill;
use Application\Entity\CombinedBill;
use SMCommon\View\Helper\Currency;

/* @var \SMCommon\View\Renderer\PhpRenderer $this */
echo $this->pageHeader('Combined Invoices');

/* @var \SMCommon\View\Helper\Table $table */
$table = $this->table();
$table->setData($this->bills);

$table->addColumn(array(
	'headTitle' 	=> 'Name',
	'dataMethod'	=> function(CombinedBill $bill) {
		return $bill->getName();
	}
));


$table->addColumn([
	'headTitle' => 'Invoices',
	'dataMethod' => function (CombinedBill $bill) {
		$output = '<ul>';
		foreach ($bill->getBills() as $subBill) {
			/* @var Bill $subBill */
			$billUrl = $this->url(
				'accounts/bills',
				array(
					'accountid' => $subBill->getAccount()->getId(),
					'billid' => $subBill->getId(),
				)
			);
			$output .= '<li>' . $this->prettyprint()->link($billUrl, $subBill->getName()) . '(' . $subBill->getAccount()->getName() . ')</li>';
		}
		$output .= '</ul>';
		return $output;
	}
]);

$table->addColumn([
	'headTitle' => 'Overview',
	'dataMethod' => function (CombinedBill $bill) {
		return $this->partial('partial/combined-bill-overview.phtml', [
			'combinedBill' => $bill
		]);
	}
]);

$table->addColumn([
	'headTitle' => 'Your Action',
	'dataMethod' => function (CombinedBill $bill) {
		$total = $bill->getTotal($this->identity());
		if ($total >= 0) {
			if ($bill->isPaid()) {
				return 'Nothing. You received ' . $this->currency($total, Currency::COLOR_POSITIVE);
			}
			else {
				return 'You receive ' . $this->currency($total, Currency::COLOR_POSITIVE);
			}
		}
		else {
			if ($bill->isPaid()) {
				return 'Nothing. You paid ' . $this->currency(abs($total), Currency::COLOR_NEGATIVE);
			} else {
				return 'You have to pay ' . $this->currency(abs($total), Currency::COLOR_NEGATIVE);
			}
		}
	}
]);


$table->addColumn(array(
	'headTitle' 	=> 'Actions',
	'dataMethod'	=> function(CombinedBill $bill) {

		if (!$bill->isPaid()) {
			// Add Purchase button
			$addUrl = $this->url(
				'bills/list-action',
				[
					'billid' => $bill->getId(),
					'action' => 'add-bill',
				]
			);
			$html = $this->prettyprint()->button($addUrl, "Add Invoice");

			// Send email button
			$emailUrl = $this->url(
				'bills/list-action',
				[
					'billid' => $bill->getId(),
					'action' => 'send-invoice-email'
				]
			);
			$html .= $this->prettyprint()->button($emailUrl, "Send Email Invoice", "warning");

			// Mark as paid
			$emailUrl = $this->url(
				'bills/list-action',
				[
					'billid' => $bill->getId(),
					'action' => 'pay'
				]
			);
			$html .= $this->prettyprint()->button($emailUrl, "Mark as Paid", "success");

			return $html;
		} else {
			return '<span class="icon-thumbs-up"></span> Paid!';
		}
	}
));

$createBillUrl = $this->url('bills/action', ['action' => 'create']);

?>


<?php echo $table; ?>
<span class="pull-right">
	<a class="btn" href="<?php echo $createBillUrl; ?>">Create Combined Invoice</a>
</span>
