<?php 
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('API Einstellungen');

$generateApiUrl = $this->url('settings/action', array('action' => 'generate-api-key'));
?>

<h3>API Schlüssel</h3>
<?php if ($this->identity()->getApiKey()) : ?>
<div class="well">
	<?php echo $this->identity()->getApiKey();?>
</div>
<?php else: ?>
<div class="alert alert-info alert-block">
	<strong>Kein API Schlüssel</strong><br>
	Sie haben noch keinen API Schlüssel. Dieser wird zum Beispiel für die iPhone Applikation verwendet. 
	<br>
	Um einen Schlüssel zu generieren <a href="<?php echo $generateApiUrl; ?>">klicken Sie hier</a>.
</div>
<?php endif;?>