<?php
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('API Settings');

$generateApiUrl = $this->url('settings/action', array('action' => 'generate-api-key'));
?>

<h3>API Key</h3>
<?php if ($this->identity()->getApiKey()) : ?>
<div class="well">
	<?php echo $this->identity()->getApiKey();?>
</div>
<?php else: ?>
<div class="alert alert-info alert-block">
	<strong>No API Key</strong><br>
	You don't have an API key yet. E.g. it is used in the iPhone application.
	<br>
	To generate an API key <a href="<?php echo $generateApiUrl; ?>">click here</a>.
</div>
<?php endif;?>