<?php 
// A partial for displaying a purchase. 

/* @var $this SMCommon\View\Renderer\PhpRenderer */
/* @var $user \Application\Entity\User */
$user = $this->user;
$email = $user->getEmailAddress();
?>
<div class="row">
	<table class="table table-condensed span5">
		<tr>
			<td>Benutzername</td>
			<td><?php echo $user->getUsername()?></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><a href="mailto:<?php echo $email;?>"><?php echo $email; ?></a></td>
		</tr>
		<tr>
			<td>Einkäufe in dieser Liste</td>
			<td>TODO</td>
		</tr>
	</table>
	
	<div class="pull-right">
		<?php echo $this->gravatar($email)?>
	</div>
</div>