<?php 
use Application\Entity\CountList;
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Strichlisten');

$table = $this->table();
$table->setData($this->lists);

$table->addColumn(array('Name', 'getName'));

$table->addColumn(array(
	'headTitle' 	=> 'Periode',
	'dataMethod'	=> function(CountList $countList) {
		$startDate =  $this->formatDate($countList->getStartDate(), FormatDate::FORMAT_DATE);
		$endDate = $this->formatDate($countList->getEndDate(), FormatDate::FORMAT_DATE);
		return $startDate . ' - ' . $endDate;
	}
));

$table->addColumn(array(
	'headTitle' 	=> 'Aktionen',
	'dataMethod'	=> function(CountList $countList) {
		$result = '';

		/*
		$editButtonGroup = array();

		// Edit button
		$editUrl = $this->url('purchase-list/list-action', array('action' => 'edit', 'purchaselistid' => $purchaseList->getId()));
		$editButtonGroup[] = array(
			'title' => 'Bearbeiten',
			'url'	=> $editUrl
		);

		// Add the edit button in the submenu again.
		$editButtonGroup[] = array(
			'title' => 'Einfkaufsliste bearbeiten',
			'url'	=> $editUrl
		);

		// Edit users (for submenu)
		$editUsersUrl = $this->url('purchase-list/user', array(
			'purchaselistid'=> $purchaseList->getId(),
		));
		$editButtonGroup[] = array(
			'title' => 'Benutzer bearbeiten',
			'url'	=> $editUsersUrl
		);

		$result .= $this->prettyprint()->splitButton($editButtonGroup);
			
		// Details about the purchase list.
		$purchasesUrl = $this->url('purchase-list/list-action', array(
			'purchaselistid' => $purchaseList->getId(),
		));
		$result .= $this->prettyprint()->button($purchasesUrl, 'Details');

		// Add purchase button
		$addPurchaseUrl = $this->url('purchase-list/purchase', array(
			'action' 			=> 'add',
			'purchaselistid'	=> $purchaseList->getId(),
		));
		$result .= $this->prettyprint()->button($addPurchaseUrl, 'Einkauf hinzufügen');
*/

		return $result;
	}
));

?>

<?php echo $table; ?>
<span class="pull-right"><a class="btn" href="<?php echo $this->url('count-list/action', array('action' => 'create')); ?>">Strichliste erstellen</a></span>

