<?php 
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->doctype(); 
?>

<html lang="en">
   <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('WGPlaner')->setSeparator(' - ') ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.custom.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
        				->prependStylesheet($this->basePath() . '/css/jquery-ui.custom.min.css')
        ?>

        <!-- Scripts -->
        <?php 
        $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',));
        $this->headScript()->prependFile($this->basePath() . '/js/application/enable-datepicker.js');
		$this->headScript()->prependFile($this->basePath() . '/js/jquery.ui.datepicker-de.js');  // German localization for Datepicker
        $this->headScript()->prependFile($this->basePath() . '/js/jquery.ui.custom.min.js');
        $this->headScript()->prependFile($this->basePath() . '/js/bootstrap.min.js');
		$this->headScript()->prependFile($this->basePath() . '/js/jquery.min.js');
        
		echo $this->headScript();
        ?>

    </head>
    <body>
    	<div class="wrap">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a href="<?php echo $this->url('home'); ?>" class="brand">WGPlaner</a>
                    <?php
                    if ($this->identity()) :
         			/* @var $navigation \Zend\View\Helper\Navigation\Menu */
		        	$navigation = $this->navigation('navigation')->menu();
		        	$navigation->setUlClass('nav');
                                $navigation->setPartial('navigation/menu');
		        	echo $navigation;
		        	 ?>
		        	<ul class="nav pull-right">
                                    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Willkommen, <?php echo $this->identity()->getFullname();?> <b class="caret"></b></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?php echo $this->url('profile');?>"><i class="icon-user"></i> Profil</a>
                                            <li><a href="<?php echo $this->url('settings');?>"><i class="icon-cog"></i> Einstellungen</a></li>
                                            <li class="divider"></li>
                                            <li><a href="<?php echo $this->url('auth', array('action' => 'logout'));?>"><i class="icon-off"></i> Logout</a></li>
                                        </ul>
                                    </li>
		        	</ul>
		        	<?php endif;?>
				</div>
            </div>
        </div> <!-- Navbar -->
        <div class="container">
        <!--  
        <?php echo $this->navigation('navigation')
        				->breadcrumbs()
        				->setMinDepth(0)
        				->setRenderInvisible(true)
        				->setPartial('navigation/breadcrumb'); 
        ?>
        -->
        <?php echo $this->content; ?>
        </div> <!-- /container -->
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
