<?php 
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->doctype(); 
?>

<html lang="en">
   <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('WGPlaner')->setSeparator(' - ') ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.custom.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
        				->prependStylesheet($this->basePath() . '/css/jquery-ui.custom.min.css')
        				->prependStylesheet($this->basePath() . '/css/magnific-popup.css')
        ?>

        <!-- Scripts -->
        <?php 
        $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',));
		$this->headScript()->prependFile($this->basePath() . '/js/jquery.ui.datepicker-de.js');  // German localization for Datepicker
        $this->headScript()->prependFile($this->basePath() . '/js/jquery.ui.custom.min.js');
        $this->headScript()->prependFile($this->basePath() . '/js/jquery.magnific-popup.min.js');
        $this->headScript()->prependFile($this->basePath() . '/js/bootstrap.min.js');
		$this->headScript()->prependFile($this->basePath() . '/js/jquery.min.js');
        
		echo $this->headScript();
        ?>

    </head>
    <body>
    	<div class="wrap">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a href="/" class="brand">WGPlaner</a>
                    <?php
         			/* @var $navigation \Zend\View\Helper\Navigation\Menu */
		        	$navigation = $this->navigation('navigation')->menu();
		        	$navigation->setUlClass('nav');
		        	echo $navigation;
		        	?>
		        	<?php if ($this->identity()) : ?>
		        	<ul class="nav pull-right">
		        		<li><a href=""><?php echo $this->identity()->getFullname(); ?></a></li>
		        	</ul>
		        	<?php endif;?>
				</div>
            </div>
        </div> <!-- Navbar -->
        <div class="container">
        <?php echo $this->navigation('navigation')
        				->breadcrumbs()
        				->setRenderInvisible(true)
        				->setPartial('navigation/breadcrumb'); 
        ?>
        <?php echo $this->content; ?>
        </div> <!-- /container -->
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
