<?php
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Einkäufe hinzufügen', $this->bill->getName());
?>

<div class="alert alert-info">
	Wählen Sie eine Zeitspanne aus. Alle Einkäufe im
	Konto <b><?php echo $this->account->getName() ?> </b>in der gegebenen Zeitspanne
	werden der Abrechnung hinzugefügt.
</div>

<?php echo $this->bootstrapForm($this->form, 'horizontal'); ?>