<?php
use Application\View\Helper\UserTable;
use Application\Entity\User;
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Benutzer', $this->bill->getName());

$table = $this->usertable();
$table->setData($this->bill->getUsers());

echo $table;

$addUserUrl = $this->url('accounts/bills', array(
	'action' 			=> 'add-user',
	'accountid'			=> $this->account->getId(),
	'billid'			=> $this->bill->getId(),
));
?>

<span class="pull-right">
	<?php echo $this->prettyprint()->button($addUserUrl, 'Benutzer hinzufügen')?>
</span>
