<?php
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader($this->bill->getName(), 'Abrechnung');

// Create the table which lists all the purchases and the user
$table = $this->purchasetable();
$table->setData($this->bill->getPurchases());
$table->addUserColumns($this->bill->getUsers());
?>

<ul class="nav nav-tabs" id="tab">
  <li class="active"><a href="#overview">Übersicht</a></li>
  <li><a href="#purchases">Einkäufe</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="overview">
    Overview
  </div>
  <div class="tab-pane" id="purchases">
    <?php echo $table ?>   
  </div>
</div>

<script>
$('#tab a').click(function (e) {
      e.preventDefault();
        $(this).tab('show');
})
</script>
