<?php
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader($this->bill->getName(), 'Abrechnung');

// Create the table which lists all the purchases and the user
$table = $this->purchasetable();
$table->setData($this->bill->getPurchases());
$table->addUserColumns($this->bill->getUsers());
?>

<ul class="nav nav-tabs" id="tab">
  <li class="active"><a href="#overview">Übersicht</a></li>
  <li><a href="#purchases">Einkäufe</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="overview">
    <h3>Gesamt</h3>
    <table class="table table-condensed table-bordered">
    <thead>
        <tr>
            <th>Einkaufssumme</th>
            <th>Total Anteile</th>
            <th>Pro Anteil</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php echo number_format($this->bill->getAmount(), 2) . " CHF";?></td>
            <td><?php echo $this->bill->getTotalUserShare();?> </td>
            <td><?php echo number_format($this->bill->getAmountPerShare(), 2) . " CHF";?></td>
        </tr>
    </tbody>
    </table>

    <h3>Benutzer</h3>

    <table class="table table-condensed table-bordered">
    <thead>
        <tr>
            <th>Benutzer</th>
            <th>Einkaufssumme</th>
            <th>Anteil</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->bill->getUsers() as $user) : ?>
        <tr>
            <td><?php echo $user->getFullname()?></td>
            <td><?php echo number_format($this->bill->getAmount($user), 2) . " CHF";?></td>
            <td>
                <?php 
                    // Share
                    $share = $this->bill->getUserShare($user)->getShare();
                    $percentage = $share / $this->bill->getTotalUserShare() * 100;
                    $percentage = number_format($percentage, 2);

                    // Amount to pay
                    $amount = $this->bill->getBillableAmount($user);
                    echo number_format($amount, 2) . " CHF ( " . $share . " / " . $percentage . "% )";
                ?> 
            </td>
            <td>
                <?php 
                    $totalPaid = $this->bill->getAmount($user);
                    $totalToPay = $this->bill->getBillableAmount($user);
                    $total = $totalPaid - $totalToPay;
                    echo number_format($total, 2) . " CHF";
                ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    </table>
  </div>
  <div class="tab-pane" id="purchases">
    <?php echo $table ?>   
  </div>
</div>
<span class="pull-right">
    <?php 
        $addUserUrl = $this->url('accounts/bills', array(
            'action' 			=> 'add-user',
            'accountid'			=> $this->account->getId(),
            'billid'			=> $this->bill->getId(),
        ));
    ?>
    <?php echo $this->prettyprint()->button($addUserUrl, 'Benutzer hinzufügen')?>
</span>


<script>
$('#tab a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
})
</script>
