<?php 
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Benutzer entfernen', $this->purchaseList->getName());

?>

<div class="alert alert-block alert-error">
<h4>Achtung!</h4>
Möchten Sie den Benutzer "<?php echo $this->user->getFullname();?>" wirklich entfernen? Dieser Vorgang kann nicht Rückgängig gemacht werden.
</div>

<?php
echo $this->bootstrapForm($this->form, 'horizontal');
?>