<?php
// A partial for displaying a user.

/* @var $this SMCommon\View\Renderer\PhpRenderer */
/* @var $user \SMUser\Entity\UserInterface */
$user = $this->user;
$email = $user->getEmailAddress();
?>
<div class="row">
	<table class="table table-condensed span5">
		<tr>
			<td>Username</td>
			<td><?php echo $user->getUsername()?></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><a href="mailto:<?php echo $email;?>"><?php echo $email; ?></a></td>
		</tr>
	</table>

	<div class="pull-right">
		<?php echo $this->gravatar($email)?>
	</div>
</div>