<?php 
use Application\Entity\PurchaseList;
use SMCommon\View\Helper\FormatDate;
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Nicht aktive Einkaufslisten');

$table = $this->table();
$table->setData($this->lists);

$table->addColumn(array('Name', 'getName'));

$table->addColumn(array(
	'headTitle' 	=> 'Periode',
	'dataMethod'	=> function(PurchaseList $purchaseList) {
		$startDate =  $this->formatDate($purchaseList->getStartDate(), FormatDate::FORMAT_DATE);
		$endDate = $this->formatDate($purchaseList->getEndDate(), FormatDate::FORMAT_DATE);
		return $startDate . ' - ' . $endDate;
	}
));

$table->addColumn(array(
	'headTitle' 	=> 'Aktionen',
	'dataMethod'	=> function(PurchaseList $purchaseList) {
		$result = '';
		
		
		return $result;
	}
));

?> 

<?php echo $table; ?>
<span class="pull-right"><a class="btn" href="<?php echo $this->url('purchase-list/action', array('action' => 'create')); ?>">Einkaufliste erstellen</a></span>