<?php 
use Application\Entity\PurchaseList;
use SMCommon\View\Helper\FormatDate;
use Application\Entity\Purchase;
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Einkäufe', $this->purchaseList->getName());

$table = $this->table();
$table->setData($this->purchaseList->getPurchases());

$table->addColumn(array(
	'headTitle' 	=> 'Datum',
	'dataMethod'	=> function (Purchase $purchase) {
		return $this->formatDate($purchase->getDate(), FormatDate::FORMAT_DATE);
	}
));

$table->addColumn(array('Geschäft', 'getStore'));


// Each user has its own column
foreach ($this->purchaseList->getUsers() as $user) {
	$table->addColumn(array(
		'headTitle' 	=> $user->getFullname(),
		'dataMethod'	=> function(Purchase $purchase) use ($user) {
			if ($purchase->getUser() == $user) {
				return number_format($purchase->getAmount(), 2) . " CHF";
			}
		}
	));
}

$table->addColumn(array(
	'headTitle' 	=> 'Aktionen',
	'dataMethod'	=> function(Purchase $purchase) {
		return $this->prettyprint()->button('', 'Details');
	}
));

echo $table;
?> 


<span class="pull-right"><a class="btn" href="<?php echo $this->url('purchase-list/action', array('action' => 'add-purchase', 'id' => $this->purchaseList->getId())); ?>">Einkauf hinzufügen</a></span>