<?php 
use Application\Entity\PurchaseList;
use SMCommon\View\Helper\FormatDate;
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Aktuelle Einkaufslisten');

$table = $this->table();
$table->setData($this->lists);

$table->addColumn(array('Name', 'getName'));

$table->addColumn(array(
	'headTitle' 	=> 'Periode',
	'dataMethod'	=> function(PurchaseList $purchaseList) {
		$startDate =  $this->formatDate($purchaseList->getStartDate(), FormatDate::FORMAT_DATE);
		$endDate = $this->formatDate($purchaseList->getEndDate(), FormatDate::FORMAT_DATE);
		return $startDate . ' - ' . $endDate;
	}
));

$table->addColumn(array(
	'headTitle' 	=> 'Aktionen',
	'dataMethod'	=> function(PurchaseList $purchaseList) {
		$result = '';
		
		$editUrl = $this->url('purchase-list/action', array('action' => 'edit', 'id' => $purchaseList->getId()));
		$result .= $this->prettyprint()->button($editUrl, 'Bearbeiten');
		
		$addPurchaseUrl = $this->url('purchase-list/action', array(
			'action' 	=> 'add-purchase', 
			'id'		=> $purchaseList->getId(),
		));
		$result .= $this->prettyprint()->button($addPurchaseUrl, 'Einkauf hinzufügen');
		
		return $result;
	}
));

$notActiveUrl = $this->url('purchase-list/action', array('action' => 'not-active'));
?> 

<div class="alert alert-info alert-block">
Hier werden nur Einkaufslisten angezeigt, bei denen das heutige Datum in der Zeitperiode liegt. Klicken Sie <b><a href="<?php echo $notActiveUrl?>">hier</a></b> um 
alle anderen Einkauflisten zu sehen.
</div>

<?php echo $table; ?>
<span class="pull-right"><a class="btn" href="<?php echo $this->url('purchase-list/action', array('action' => 'create')); ?>">Einkaufliste erstellen</a></span>