<?php 
use Application\Entity\PurchaseList;
use SMCommon\View\Helper\FormatDate;
/* @var $this SMCommon\View\Renderer\PhpRenderer */
echo $this->pageHeader('Einkäufe', $this->purchaseList->getName());

?> 


<span class="pull-right"><a class="btn" href="<?php echo $this->url('purchase-list/action', array('action' => 'add-purchase', 'id' => $this->purchaseList->getId())); ?>">Einkauf hinzufügen</a></span>