<?php
/* @var $this SMCommon\View\Renderer\PhpRenderer */
$allUrl = '<a href="?all=1">All purchases</a>';
$myUrl = '<a href="?all=0">My purchases</a>';
echo $this->pageHeader('Not verified purchases', $allUrl . " | " . $myUrl);

$purchases = $this->purchases;
?>

<?php 
/* @var $purchase Application\Entity\Purchase */
foreach ($purchases as $purchase): 
?>


<div class="row">
    <div class="<?php echo $purchase->hasReceipt() ? 'span8' : 'span12'?>">
	<h3>Details</h3>
		<?php
		echo $this->partial('partial/purchase', array(
		    'purchase' => $purchase,
		    ));
		?>
    </div>

    <?php if ($purchase->hasReceipt()): ?>
    <div class="span4">
	<h3>Receipt</h3>
	<img src="<?php echo $this->receiptImage($purchase); ?>">
    </div>
    <?php endif; ?>
</div>
<div class="row">
    <div class="well">
		<?php
		$params = array(
		    'action' => 'edit',
		    'accountid' => $purchase->getAccount()->getId(),
		    'purchaseid' => $purchase->getId()
		);
		$editUrl = $this->url('accounts/purchases', $params);
		echo $this->prettyprint()->button($editUrl, 'Bearbeiten');

		// Delete button
		$params = array(
		    'action' => 'delete',
		    'accountid' => $purchase->getAccount()->getId(),
		    'purchaseid' => $purchase->getId()
		);
		$deleteUrl = $this->url('accounts/purchases', $params);
		echo $this->prettyprint()->button($deleteUrl, 'Delete', 'danger');

		?>
	    <?php
	    $params = array(
		'action' => 'verify',
		'accountid' => $purchase->getAccount()->getId(),
		'purchaseid' => $purchase->getId()
	    );
	    $verifyUrl = $this->url('accounts/purchases', $params);
	    echo $this->prettyprint()->button($verifyUrl, 'Verifiy', 'success');
	    ?>
	</div>
</div>


<?php endforeach; ?>